version: "3.8"

services:
  db:
    image: mysql:8.4.0
    container_name: ecoride-db
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d


  front:
    build:
      context: ./frontend-ecoride
    restart: always
    container_name: frontend-ecoride
    ports:
      - "80:80"
    depends_on:
      - back

volumes:
  mysql-data:



